### ISSUE TITLE
Collaboration among groups of people

### ISSUE THREAD

**Issue by sergio4457** [ChristianMarzahl/Exact#10]
Hi I have accessed the EXACT label Server. A collaborator and I want to label some images. But we cannot find a way to allow the other into the set to collaborate. Is there a guideline for that? 
Thank you, and your work is great

**Comment by ChristianMarzahl** [comment]
Hi,

the following video give you an introduction to the team and user options:
https://www.youtube.com/watch?v=T2j5-NUhQFA&list=PLuA57h8TbJncBwIg_IJIP61EeAdYt4DSs&index=4

https://www.youtube.com/playlist?list=PLuA57h8TbJncBwIg_IJIP61EeAdYt4DSs

If you have any question please feel free to ask. 


With kind regards,
Christian
