### ISSUE TITLE
Filled Polygons

### ISSUE THREAD

**Issue by FraukeWilm** [ChristianMarzahl/Exact#11]
Hello Christian,

it would be really cool if Exact could offer the possibility to visualize annotations as filled polygons. 
Thank you for your great tool! 

Kind regards
Frauke

**Comment by aaichert** [comment]
We at SHS second this. Ideally, the fill color could be different from the line color and support transparency.

An additional "fullcolor" property in products that stores an arbitrary RGBA hex code would suffice.

**Comment by ChristianMarzahl** [comment]
Fixed in version: https://github.com/ChristianMarzahl/Exact/pull/67/
