### ISSUE TITLE
Error Launching Exact with Docker Compose File

### ISSUE THREAD

**Issue by bnapora** [ChristianMarzahl/Exact#15]
Having an issue launching Exact in Docker.

Using Docker Desktop for Windows 10
Clone GIT Repository
Run following command from CLI in repo folder: docker-compose -f docker-compose.yml up -d --build

Container is built successfully, but get following error when it starts.  Any help would be appreciated.

ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/usr/src/exact/entrypoint.sh\": stat /usr/src/exact/entrypoint.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by ChristianMarzahl** [comment]
Dear Brian,

can you please try "docker-compose -f docker-compose.prod.yml up -d --build"

The build and start process runs on GitHub successfully. 
https://github.com/ChristianMarzahl/Exact/runs/1210078218?check_suite_focus=true

This error can occur when you save the ".sh" file under windows with the wrong line ending format or you git clone under windows changes the line ending format. 

With kind regards,
Christian

**Comment by bnapora** [comment]
Using prod compose file worked.  Thanks so much for the help.
