### ISSUE TITLE
Error message on deleting images

### ISSUE THREAD

**Issue by maubreville** [ChristianMarzahl/Exact#24]
When deleting an image in annotation mode, the URL is not updated, thus you can receive an error 404:

Page not found (404)
Request Method: | GET
Request URL: http://127.0.0.1:8000/annotations/4/
Raised by: exact.annotations.views.annotate

**Comment by ChristianMarzahl** [comment]
Fixed: https://github.com/ChristianMarzahl/Exact/pull/26
