### ISSUE TITLE
Image classification key maps inverted

### ISSUE THREAD

**Issue by ma0ho** [ChristianMarzahl/Exact#28]
When labelling a classification dataset with two classes, the key mapping for assigning the classes is displayed as ```Shift-1``` and ```Shift-2```. However, ```Shift-1``` assigns the second class, while ```Shift-2``` assigns the first one.

**Comment by ChristianMarzahl** [comment]
Dear User,

thank you for your valuable feedback. The key ordering is defined by the sort value under "Administration" -> "Annotation Types". 


![image](https://user-images.githubusercontent.com/22664224/109115350-3d4c7d00-773f-11eb-8939-65b0cc899597.png)

I hope this answers your question. 

With kind regards,
Christian

**Comment by ma0ho** [comment]
Thanks for the fast reply! Mayby I was a bit unclear: The problem is that the displayed keymap does not correspond to what actually happens, when you press those keys. For example, consider this:

![grafik](https://user-images.githubusercontent.com/1632554/109122198-86ed9580-7748-11eb-9f6e-219daac524a6.png)

Here, ```Shift-1``` should assign ```Class_Crack``` according to the specs. However, pressing ```Shift-1``` assigns ```Class_Inactive```. This is fixed by changing the sort order, because this changes the ordering of classes but not the ordering of keybindings. However, from my perspective, the displayed keybindings should always do what they are supposed to. Otherwise, things are very confusing..

**Comment by ChristianMarzahl** [comment]
Fixed: https://github.com/ChristianMarzahl/Exact/commit/68d870ea06912c992c69e376b346aa6ce32a1a33
