### ISSUE TITLE
Provide REST API Calls for Online/Offline sync

### ISSUE THREAD

**Issue by maubreville** [ChristianMarzahl/Exact#3]
Calls requested are:

- List products available in a dataset
- Add annotation type within product
- Remove annotation type (lower prio, just for completeness)
- Retrieve WSI

**Comment by maubreville** [comment]
Implemented. Close issue after merge.

**Comment by ChristianMarzahl** [comment]
https://github.com/ChristianMarzahl/EXACT-Sync
