### ISSUE TITLE
Install with Docker fails, because python version < 3.8

### ISSUE THREAD

**Issue by Tyde** [ChristianMarzahl/Exact#32]
Hi I tried to install Exact using docker-compose, but it fails in the following step:

    RUN pip3 install --no-cache /wheels/*

When it wants to collect the transformations package:

    Collecting transformations
    Downloading transformations-2020.1.1.tar.gz (44 kB)

I get a RuntimeError:

    RuntimeError: Python version >= 3.7 required.

As the Dockerfile is using ubuntu 18.04 it is only using Python 3.6.9 which then fails the requirement

**Comment by ChristianMarzahl** [comment]
Dear Tyde,

thank you for the bug report. I will look into it. 

With kind regards,
Christian

**Comment by ChristianMarzahl** [comment]
Fixed: https://github.com/ChristianMarzahl/Exact/commit/68d870ea06912c992c69e376b346aa6ce32a1a33
