### ISSUE TITLE
After prod Docker install: ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

### ISSUE THREAD

**Issue by Tyde** [ChristianMarzahl/Exact#33]
Hi, 

I installed the prod version with docker-compose. It seemed to work fine. The log for the first command `docker-compose -f docker-compose.prod.yml up -d --build` can be found here: https://gist.github.com/Tyde/26a2bf733ecb5419bb4a1c20a50ed60e 

When I try to run the second command: `docker-compose -f docker-compose.prod.yml exec web python manage.py migrate --noinput` I do get the following error:
Traceback (most recent call last):
```
File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

**Comment by ChristianMarzahl** [comment]
Dear Tyde,

sorry for the inaccuracy in the documentation. 
Please use python3 I will update the documentation immediately.

```
docker-compose -f docker-compose.prod.yml exec web python3 manage.py migrate --noinput
```

With kind regards,
Christian

**Comment by ChristianMarzahl** [comment]
Fixed: https://github.com/ChristianMarzahl/Exact/commit/4d9c9a6a4bc4ced349c8051bc6a316761cf758c7
