### ISSUE TITLE
Wrong link in README.md

### ISSUE THREAD

**Issue by maubreville** [ChristianMarzahl/Exact#4]
The following link does not/no longer work:

Our production uwisgi config can be found at https://github.com/fsinfuhh/mafiasi-rkt/blob/master/imagetagger/uwsgi-exact.ini

**Comment by ChristianMarzahl** [comment]
Fixed:

https://github.com/ChristianMarzahl/Exact/commit/961a5dbf2798132dd1803ef50fccaf2e5a50129d
