### ISSUE TITLE
Exception when last action image was deleted

### ISSUE THREAD

**Issue by maubreville** [ChristianMarzahl/Exact#6]
When the image shown in last_action was deleted, it is no longer possible to use exact, since there is an error immediately after login:

django.urls.exceptions.NoReverseMatch: Reverse for 'team' with arguments '('',)' not found. 1 pattern(s) tried: ['users/team/(\\d+)/$']

Most likely, the team of the image can no longer be looked up, which causes the error.

**Comment by ChristianMarzahl** [comment]
Fixed:

Cascade on delete was not set

https://github.com/ChristianMarzahl/Exact/commit/eaa4c0e652102400f6ad8d132472eb1a04bd10b4
