### ISSUE TITLE
Annotations being only partially saved if <enter> not hit

### ISSUE THREAD

**Issue by maubreville** [ChristianMarzahl/Exact#66]
When adding rectangular annotations (only checked with those) within an image, these are only reliably stored into the database when "enter" is hit. While this is the intended workflow, the annotations are shown on the UI regardless if enter was hit or not.

In the following image, the left annotations were all clicked only a single time (and are shown all), without hitting enter at any time:
![image](https://user-images.githubusercontent.com/10051592/135422581-99b66e86-530a-4964-93c2-aad76e6543c5.png)

This is the result in the database:
![image](https://user-images.githubusercontent.com/10051592/135422534-fcc0c227-09bd-4f3f-9364-1b9bd8247c3b.png)

Since the annotations are successfully shown, it is not unlikely that users deviate from the instructions and don't hit enter. 

**I would encourage to show annotations only after successful storage in the database (i.e. on server response), to have DB and UI always in sync, if this is not already the case.**

**Comment by maubreville** [comment]
The slide (for reference) is: https://exact.cs.fau.de/annotations/19219/?frame=1&xmin=5272&ymin=3975&xmax=7182&ymax=5121

**Comment by ChristianMarzahl** [comment]
Dear User,

*I would encourage to show annotations only after successful storage in the database (i.e. on server response), to have DB and UI always in sync, if this is not already the case.*
There is a notification at the bottom if the annotation was created successfully.  
![image](https://user-images.githubusercontent.com/22664224/135443702-84c62228-1816-4fcf-a812-ef74ad6d281f.png)

**Comment by ChristianMarzahl** [comment]
Fixed in version: https://github.com/ChristianMarzahl/Exact/pull/67/
