### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by StormyaP** [ChristianMarzahl/Exact#71]
Every time I want to create a new account, the internal server error (500) appears but when I want to register the account again, it shows the user name is already registered.
![image](https://user-images.githubusercontent.com/34170154/140944601-19fd5cf6-a3a7-4a24-b1fc-fd7c820d367d.png)
If possible, can you please delete the account with the user name "gu", "gu0923" and "gu1994"? Those are ghost accounts that I just created. Thanks.
![image](https://user-images.githubusercontent.com/34170154/140944868-23331608-f685-4c4c-b153-261b19da722c.png)

**Comment by ChristianMarzahl** [comment]
Dear StormyaP,

Thanks for reporting this error. We fixed it, and now you should be able to create an account.

With kind regards,
Christian
