### ISSUE TITLE
Image annotation cannot be displayed correctly

### ISSUE THREAD

**Issue by get-Resource** [ChristianMarzahl/Exact#9]
@ChristianMarzahl I modified Python 3 running, allowed hosts, mapped IP, and tried local docker compose up-d. after success, I created and uploaded the image set, but the image could not be displayed correctly. The example is as follows.
![image](https://user-images.githubusercontent.com/51358196/81486363-e4caf280-9286-11ea-80b6-2e4d6a114147.png)

**Comment by get-Resource** [comment]
At the same time, when clicking the button, the browser does not send a request. For example, when clicking Create comment type and create a new product, it often occurs that the browser does not send a request.

**Comment by ChristianMarzahl** [comment]
Hi,

please rebuild the Docker container, I fixed a huge bug yesterday evening regarding the conversion and upload of images.

Second: You have to add "Products" and "AnnotationTypes" to actually annotate something. 

https://www.youtube.com/watch?v=4XdWLaqy9UA&list=PLuA57h8TbJncBwIg_IJIP61EeAdYt4DSs&index=4&t=0s

With kind regards,
Christian

**Comment by ChristianMarzahl** [comment]
@get-Resource Please leaf me a note if the problem still exists or is fixed now.

With kind regards,
Christian

**Comment by get-Resource** [comment]
thank. have already been solved
