### ISSUE TITLE
Creation of images directory required. 

### ISSUE THREAD

**Issue by maubreville** [ChristianMarzahl/Exact#90]
Just tried to install Exact on a fresh instance from the README, and apparently it required the creation of the "images" folder in Exact/exact/images before running the migration.

I think a fix will be to just add an empty folder to github so that this will be created automatically, or to add it to the README.

**Comment by ChristianMarzahl** [comment]
Moin,

Could you please provide some details about your operating system? Sound like EXACT does not have the rights to create the image folder? 


With kind regards,
Christian

**Comment by maubreville** [comment]
It's a dockered Linux instance, and all the required writing priviledges were available. Creating the folder via a simple mkdir solved the problem.
